# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'FamilyFinances'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: ''

menu:
- {name: 'About us',           url: 'about-us'}
- {name: 'Blog',               url: 'blog'}
- {name: 'Events',             url: 'events'}
- {name: 'Publications',       url: 'publications'}
- {name: 'Take Part',         url: 'take-part'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
 - {icon: 'envelope',  type: solid,   link:   'mailto:family-finances-project@york.ac.uk'}
 #- {icon: 'x-twitter', type: brands,  link:   'https://twitter.com/'}
 #- {icon: 'bluesky',   type: brands,  link:   'https://bsky.app/'}
# - {icon: 'bluesky', link:    'https://bsky.app/'}
# - {icon: 'facebook', link:   'https://www.facebook.com/'}
# - {icon: 'instagram', link:  'https://instagram.com/'}
# - {icon: 'rss-square', link: 'feed.xml'}
# - {icon: 'rss-square', link: 'rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Please feel free to share!'

related_posts: 'Related posts'

post_date_prefix: 'Published on'
